name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: pip install .

    - name: Run Smoke Test
      # We use a tiny model to make the CI fast
      run: hf-bench sshleifer/tiny-gpt2 --tokens 8